title: ArtFire.com Scam
description: I was scammed on ArtFire.com. I created this website to warn others about their shady and negligent business practices. Read more below for how you may be scammed buying items from ArtFire.com.

color:
  primary-dark: '#000000'
  links: '#219ab3'

markdown: kramdown
permalink: pretty
